name: LAPRAS Card

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-card:
    name: LAPRAS Card
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo  # タイムゾーンを日本時間に設定
    steps:
      - name: Set up JA_JP locale
        run: |
          sudo apt-get update
          sudo apt-get install -y locales
          sudo locale-gen ja_JP.UTF-8
          sudo update-locale LANG=ja_JP.UTF-8
      - uses: kawamataryo/lapras-card-readme@main
        with:
          SHARE_ID: "kuroneko913"
          # 以下オプション
          # https://lapras-card-generator.vercel.app でカスタマイズしたデザインを設定可能
          # ICON_FIRST: "#030E21"
          # ICON_SECOND: "#1688BF"
          # BACKGROUND_FIRST: "#020E27"
          # BACKGROUND_SECOND: "#0E5593"
          LANG: "en"
          # CARD_WIDTH: "400"
          # UPDATE_TIME: "true"
          # README_FILE: "README.md"
          # IS_CENTER: "true"
          # ALTERNATIVE_TEXT: "Score of {SHARE_ID} on LAPRAS"
